### ISSUE TITLE
dev.mathiasbuus public domain?

### ISSUE THREAD

**Issue by pechitook** [mafintosh/telephone#2]
Any chance you can switch this to your actual public IP on Digital Ocean so we can test easier? Really want to try this out, but no one around :)

**Comment by pechitook** [comment]
Turns out that the README is missing the tld. This should be updated:

```
telephone --hole-puncher dev.mathiasbuus.eu:23232 --channel my-channel
```

Thanks :)

**Comment by mafintosh** [comment]
Fixed in master. Thanks for reporting this! :+1:
